### ISSUE TITLE
plg not opening frame macOS

### ISSUE THREAD

**Issue by andrewnc** [LLNL/yorick#25]
I am trying to generate a very simple plot.

```plg, span(0,1,200)^2, span(0,1,200)```

But it hangs and never plots. As a new user, I would love to figure out this functionality, and I appreciate any help.

**Comment by dhmunro** [comment]
Note that yorick is obsolete.  Please use scipy (scipy.org), with the npplus package from pypi.org and the qnd package from github.com/LLNL/qnd for legacy yorick compatibility.

Setting up a proper MacOS X X11 environment has become quite difficult as Apple tries to distance itself farther and farther from Linux, and debugging it requires great expertise.  In fact, even getting scipy's matplotlib graphics working under MacOS can be quite challenging, and you should spend your time getting that working instead of messing with yorick.
